### ISSUE TITLE
TrackDef is undefined

### ISSUE THREAD

**Issue by raff** [bspaans/bleep#12]
Just trying to build and I get an error here:
https://github.com/bspaans/bleep/blob/4c0447ef057592f8df74dcb8b22bd072582c0a37/sequencer/definitions/sequencer.go#L18

```
# github.com/bspaans/bleep/sequencer/definitions
sequencer/definitions/sequencer.go:18:25: undefined: TrackDef

```

**Comment by AlexanderMatveev** [comment]
Looks like project abandoned

**Comment by bspaans** [comment]
Forgot to push a file apparently. Fixed now.
